doctrine:
    dbal:
        default_connection: example
        connections:
            example:
                url: '%env(resolve:EXAMPLE_DB_URL)%'
                driver: 'pdo_mysql'
                server_version: '10.4'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
    orm:
        default_entity_manager: example
        entity_managers:
            example:
                connection: example
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Example'
                        prefix: 'App\Entity\Example'
                        alias: App

