version: '3.7'

networks:
  example-network:
    driver: bridge

services:
  db:
    image: docker.io/bitnami/mariadb:10.4.24
    ports:
      - '3306:3306'
    volumes:
      - 'db-data:/bitnami/mariadb'
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=example
      - MARIADB_PASSWORD=example
      - MARIADB_DATABASE=example
    networks:
      - example-network
  php:
    build: ./docker/php
    ports: ['9000:9000']
    volumes: ['.:/var/www/symfony:cached']
    environment:
      - APP_ENV=dev
      - KERNEL_CLASS=App\Kernel
      - EXAMPLE_DB_URL=mysql://example:example@db/example?serverVersion=mariadb-10.4.24
    depends_on:
      - db
    networks:
      - example-network
  nginx:
    build: ./docker/nginx
    ports: ['8010:8010']
    volumes: ['.:/var/www/symfony:cached']
    links:
      - php
    networks:
      - example-network
    expose:
      - 8010

volumes:
  db-data:
    driver: local
